name: Go

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: download
      run: go mod download
      
    - name: download
      run: go build -o ./notfli

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Your commit message'
        add: './notfli'
      
    
